Added two categories: Calculus and Arrows, added some symbols, partial derivative and many arrows
maximmcnair/copypastemathjax pull request #1
Opened 2022-12-12 22:45 UTC by daniel-jakob

2022-12-12 22:50 UTC, daniel-jakob commented
I can't see why vercel failed its check. I don't immediately see any errors in my additions.

2022-12-13 13:06 UTC, maximmcnair requested changes
Thanks for spending the time adding these! There are a couple of typescript issues that I've found, everything else looks great though

2022-12-13 13:06 UTC, maximmcnair commented on src/lib/expressions.ts
> +  Calculus = 'Calculus'
You'll need a comma on the end of this line

2022-12-13 13:06 UTC, maximmcnair commented on src/lib/expressions.ts
> +    tags: ["Category.Calculus"],
These should be typescript enums rather than strings. So this line would be:
`    tags: [Category.Calculus],`

2022-12-13 13:06 UTC, maximmcnair commented on src/lib/expressions.ts
> +    tags: ["Category.Calculus"],
Same as above:
`    tags: [Category.Calculus],`

2022-12-13 13:14 UTC, maximmcnair commented
@daniel-jakob Just realised the "template" I left in has strings for the tags. That's quite misleading, I'll get that changed today.

2022-12-13 15:29 UTC, daniel-jakob commented
This is my first time resolving a conflict and doing a change request haha, not sure if what I've done now is correct, but I fixed those two small errors and committed to my main.

2022-12-13 16:51 UTC, maximmcnair commented
This looks good, thanks for making those changes. Merging now

2022-12-13 16:51 UTC, merged